# Generated by Django 3.0.8 on 2020-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproblem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postproblem',
            name='problem',
            field=models.TextField(),
        ),
    ]
