# Generated by Django 3.0.8 on 2020-08-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_auto_20200818_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproblem',
            old_name='problem',
            new_name='problem_title',
        ),
        migrations.RemoveField(
            model_name='postproblem',
            name='title',
        ),
    ]
